# Generated by Django 5.0.6 on 2024-11-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lca3app', '0002_workoutmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
